# Generated by Django 2.0.5 on 2018-05-20 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='need',
            name='pledges',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pledges',
        ),
        migrations.AddField(
            model_name='pledge',
            name='need',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Need'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pledge',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile'),
            preserve_default=False,
        ),
    ]
