# Generated by Django 2.0.5 on 2018-05-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180520_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='address',
            field=models.TextField(default='123 Main St Sunnyvale, CA', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='need',
            name='description',
            field=models.TextField(default='Earthquake response 2018', max_length=140),
            preserve_default=False,
        ),
    ]
