# Generated by Django 2.0.5 on 2018-05-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180520_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='is_reimbursed',
            field=models.BooleanField(default=False),
        ),
    ]
