# Generated by Django 2.0.5 on 2018-05-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pledge_is_reimbursed'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
