# Generated by Django 2.0.5 on 2018-05-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_depot_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='city',
            field=models.CharField(default='Sunnyvale', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depot',
            name='state',
            field=models.CharField(default='CA', max_length=140),
            preserve_default=False,
        ),
    ]
